---
- name: Playbook to change a systemd state
  hosts: all
  tasks:
    - name: Update a systemd service
      ansible.builtin.systemd_service:
        state: "{{ state }}"
        name: "{{ service_name }}"
